name: tests
on: [push, pull_request]
permissions: {}
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        uses: actions/setup-node@v3
        with:
          node-version: '20.6.1'
      - run: npm install
        shell: bash
      - name: Run Test Suite
        run: |
          npx hardhat test
          npx hardhat coverage
          cat gas-report.txt
